# Generated by Django 4.2.14 on 2024-08-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_faqheaders_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='headers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqheaders', to='website.faqheaders'),
        ),
    ]
