# Generated by Django 4.2.14 on 2024-08-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_legal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumTitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='premium')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Premium Categories',
            },
        ),
    ]
