# Generated by Django 4.2.14 on 2024-08-05 13:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_premiumtitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='premium')),
                ('body', ckeditor.fields.RichTextField()),
                ('premium_headers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiumheaders', to='website.premiumtitles')),
            ],
            options={
                'verbose_name_plural': 'Premium Services',
            },
        ),
    ]
