# Generated by Django 4.2.14 on 2024-08-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='premium',
            name='maintitle',
            field=models.CharField(default='premium header', max_length=50),
        ),
    ]
