# Generated by Django 4.2.14 on 2024-08-04 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availmodule', '0002_alter_availability_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 8, 11)),
        ),
    ]
